### ISSUE TITLE
CPU Quiet Governor card doesn't show description

### ISSUE THREAD

**Issue by Beta1440** [Grarak/KernelAdiutor#381]
Here is the relevent commit: https://github.com/Grarak/KernelAdiutor/commit/c5fe87b847eae734a06984deba4b50aaa6a99790

And here is a screenshot showing the CPU Quiet Governor card in the bottom right cornor.
![screenshot_cpu_quiet_governor](https://cloud.githubusercontent.com/assets/5178705/13383306/b724e64a-de55-11e5-91c1-a44757333100.jpeg)

**Comment by yoinx** [comment]
That's because it has the description of the governor in the Dswitch card. https://github.com/Grarak/KernelAdiutor/commit/c5fe87b847eae734a06984deba4b50aaa6a99790#diff-99645d724d331fe6b5443bf089b2329eR266

You apparently don't have the option for the card. It would be pretty simple to re-use the same summary though for the other spot.

**Comment by Grarak** [comment]
fixed in beta

**Comment by Beta1440** [comment]
On the beta this issue still exists. I belive its because CPU Quiet enable is in a different file. Below is the path to check if CPU quiet is enabled on my device.
/sys/devices/system/cpu/cpuquiet/tegra_cpuquiet/enable

**Comment by Grarak** [comment]
https://github.com/Grarak/KernelAdiutor/commit/88e561e58516e459b29aa762308ba03512fe52f2
